### ISSUE TITLE
Can we meet later today?

### ISSUE THREAD

**Issue by eickenberg** [Chris-Pedersen/LearnableWavelets#36]
Sorry for the unusual way of contacting -- i am on my phone and don't have your nyu address there.
Could we meet eg 6pm est today? Or tomorrow?

**Comment by eickenberg** [comment]
That explains why my email bounced - i forgot the dot.

Would you be able to meet 10am est on Friday?

**Comment by Chris-Pedersen** [comment]
Yes sure - we are also thinking about meeting with the CDS students at 5pm on Weds, happy to chat after that, or meet again on Friday?

**Comment by eickenberg** [comment]
odd - I think this message is from May, but it only now appeared on github?

**Comment by eickenberg** [comment]
can't do wednesday afternoon, but can catch up next time, or we meet
thursday or friday
